services:
  postgres:
    image: postgres:18.4
    environment:
      POSTGRES_DB: habit_tracker
      POSTGRES_USER: habit_tracker
      POSTGRES_PASSWORD: habit_tracker
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: