spring.application.name=habit-tracker

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/habit_tracker}
spring.datasource.username=${DB_USERNAME:habit_tracker}
spring.datasource.password=${DB_PASSWORD:habit_tracker}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false