CREATE TABLE habit_completions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    habit_id BIGINT NOT NULL REFERENCES habits(id),
    completion_date DATE NOT NULL,

    CONSTRAINT uq_habit_completions_habit_date
        UNIQUE (habit_id, completion_date)
);
